apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server-john-doe-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-server-john-doe-deployment
  template:
    metadata:
      labels:
        app: fastapi-server-john-doe-deployment
    spec:
      containers:
        - image: ttl.sh/john_doe_iris/fastapi-server-image:latest
          imagePullPolicy: Always
          name: fastapi-server-deployment
          resources:
            requests:
              memory: "4Gi"
              cpu: "4"
            limits:
              memory: "4Gi"
              cpu: "4"
          ports:
            - containerPort: 8000
              name: fastapi-server-deployment
          volumeMounts:
            - name: model-volume
              mountPath: /model
      volumes:
        - name: model-volume
          persistentVolumeClaim:
            claimName: model-pvc
