apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-server-deployment
  template:
    metadata:
      labels:
        app: fastapi-server-deployment
    spec:
      containers:
      - name: fastapi-server-deployment
        image: ttl.sh/john_doe_iris/fastapi-server-image:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: model-volume
          mountPath: /model
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc
      # volumes:
      # - name: model-volume
      #   hostPath:
      #     path: /Users/reighns/Downloads/iris/model
      #     type: Directory