version: '3'
x-logging:
  &default-logging
  options:
    max-size: "100m"
    max-file: "5"
  driver: json-file
services:
  prefect-agent:
    build:
      context: .
    environment:
      - PREFECT__CLOUD__AUTH_TOKEN=${PREFECT__CLOUD__AUTH_TOKEN}
      - PREFECT__CLOUD__AGENT__WORKER_QUEUE=${PREFECT__CLOUD__AGENT__WORKER_QUEUE}
    command:
      [
        "prefect",
        "agent",
        "start",
        "--work-queue",
        "${PREFECT__CLOUD__AGENT__WORKER_QUEUE}"
      ]
