name: "Continuous Integration (CI)"
description: "DevOps: Run CI checks on pull requests and pushes to main branch."
runs:
  using: "composite"
  steps:
    - name: Run Bandit Security Check
      run: |
        bash ./scripts/devops/ci/ci_security_bandit.sh \
          --severity-level=low \
          --format=json \
          --output=bandit_results.json \
          common_utils
      shell: bash
      continue-on-error: true
    - name: Run Linter Check
      run: |
        bash ./scripts/devops/ci/ci_linter_pylint.sh \
          --rcfile=pyproject.toml \
          --fail-under=10 \
          --score=yes \
          --output-format=json:pylint_results.json,colorized \
          common_utils
      shell: bash
      continue-on-error: true
    - name: Run Formatter Black Check
      run: |
        bash ./scripts/devops/ci/ci_formatter_black.sh \
          --check \
          --diff \
          --color \
          --verbose \
          common_utils
      shell: bash
      continue-on-error: true
    - name: Run Formatter Isort Check
      run: |
        bash ./scripts/devops/ci/ci_formatter_isort.sh \
          --check \
          --diff \
          --color \
          --verbose \
          common_utils
      shell: bash
      continue-on-error: true
    - name: Run MyPy Type Check
      run: |
        bash ./scripts/devops/ci/ci_typing_mypy.sh \
          --config-file=pyproject.toml \
          common_utils \
          | tee mypy_results.log
      shell: bash
      continue-on-error: true
    - name: Upload Check Results
      uses: actions/upload-artifact@v3
      with:
        name: check-results
        path: |
          ./bandit_results.json
          ./pylint_results.json
          ./mypy_results.log
    - name: Check for any failure
      run: |
        if [[ "${{ failure() }}" == "true" ]]; then
          echo "One or more steps failed, failing job"
          exit 1
        fi
      shell: bash