name: "Continuous Integration (CI)"
description: "DevOps: Run CI checks on pull requests and pushes to main branch."
runs:
  using: "composite"
  steps:
    - name: Run Bandit Security Check
      run: |
        bash ./scripts/devops/ci/ci_security_bandit.sh \
          --severity-level=low \
          --format=json \
          --output=bandit_results.json \
          common_utils \
          examples
      shell: bash
    - name: Run Linter Check
      run: |
        bash ./scripts/devops/ci/ci_linter_pylint.sh \
          --rcfile=pyproject.toml \
          --fail-under=10 \
          --score=yes \
          --output-format=json:pylint_results.json,colorized \
          common_utils \
          examples
      shell: bash
    - name: Run Formatter Black Check
      run: |
        bash ./scripts/devops/ci/ci_formatter_black.sh \
          --check \
          --diff \
          --color \
          --verbose \
          common_utils \
          examples
      shell: bash
    - name: Run Formatter Isort Check
      run: |
        bash ./scripts/devops/ci/ci_formatter_isort.sh \
          --check \
          --diff \
          --color \
          --verbose \
          common_utils \
          examples
      shell: bash