name: Daily Email

on:
  schedule:
    - cron: "0 11 * * *" # Run this workflow every day at 11:00 AM UTC

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Have you done what you wanted to do today?
          body: Check GitHub!
          to: ${{ secrets.MAIL_USERNAME }}
          from: ${{ secrets.MAIL_USERNAME }}
